//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class AllowSyncType
    {
        private AllowSyncType(string value) { Value = value; }

        public string Value { get; private set; }

        public static AllowSyncType Boolean { get { return new AllowSyncType("boolean"); } }

        public static AllowSyncType AllowSync3 { get { return new AllowSyncType("AllowSync_3"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(AllowSyncType v) { return v.Value; }
        public static AllowSyncType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "AllowSync_3": return AllowSync3;
                default: throw new ArgumentException("Invalid value for AllowSyncType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((AllowSyncType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(AllowSync.AllowSyncConverter))]
    public class AllowSync
    {
        public AllowSync(AllowSyncType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public AllowSync3? AllowSync3 { get; set; }

        public AllowSyncType Type { get; set; }
        public static AllowSync CreateBoolean(bool boolean)
        {
            AllowSyncType typ = AllowSyncType.Boolean;

            AllowSync res = new AllowSync(typ);
            res.Boolean = boolean;
            return res;
        }
        public static AllowSync CreateAllowSync3(AllowSync3 allowSync3)
        {
            AllowSyncType typ = AllowSyncType.AllowSync3;

            AllowSync res = new AllowSync(typ);
            res.AllowSync3 = allowSync3;
            return res;
        }

        public class AllowSyncConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(AllowSync);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new AllowSync(AllowSyncType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new AllowSync(AllowSyncType.AllowSync3)
                    {
                        AllowSync3 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AllowSync3>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AllowSync3), new AllowSync(AllowSyncType.AllowSync3), "AllowSync3"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                AllowSync res = (AllowSync)value;

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.AllowSync3 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AllowSync3));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}