//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CanAutoSync2Type
    {
        private CanAutoSync2Type(string value) { Value = value; }

        public string Value { get; private set; }

        public static CanAutoSync2Type One { get { return new CanAutoSync2Type("1"); } }

        public static CanAutoSync2Type Boolean { get { return new CanAutoSync2Type("boolean"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CanAutoSync2Type v) { return v.Value; }
        public static CanAutoSync2Type FromString(string v) {
            switch(v) {
                case "1": return One;
                case "boolean": return Boolean;
                default: throw new ArgumentException("Invalid value for CanAutoSync2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CanAutoSync2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(CanAutoSync2.CanAutoSync2Converter))]
    public class CanAutoSync2
    {
        public CanAutoSync2(CanAutoSync2Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public One? One { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        public CanAutoSync2Type Type { get; set; }
        public static CanAutoSync2 CreateOne(One one)
        {
            CanAutoSync2Type typ = CanAutoSync2Type.One;

            CanAutoSync2 res = new CanAutoSync2(typ);
            res.One = one;
            return res;
        }
        public static CanAutoSync2 CreateBoolean(bool boolean)
        {
            CanAutoSync2Type typ = CanAutoSync2Type.Boolean;

            CanAutoSync2 res = new CanAutoSync2(typ);
            res.Boolean = boolean;
            return res;
        }

        public class CanAutoSync2Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CanAutoSync2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CanAutoSync2(CanAutoSync2Type.One)
                    {
                        One = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<One>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(One), new CanAutoSync2(CanAutoSync2Type.One), "One"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new CanAutoSync2(CanAutoSync2Type.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CanAutoSync2 res = (CanAutoSync2)value;

                if (res.One != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.One));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}