//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;

    public class CloudServerResponse
    {
        [JsonProperty("address")]
        public string? Address { get; set; }

        [JsonProperty("name")]
        public string? Name { get; set; }

        [JsonProperty("port")]
        public long? Port { get; set; }

        [JsonProperty("scheme")]
        public string? Scheme { get; set; }
    }
}