//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;

    /// <summary>
    /// Voice activity detection availability flag returned by PMS.<br/>
    /// PMS returns this as string values (`"0"` or `"1"`) instead of a JSON boolean.
    /// </summary>
    public enum HasVoiceActivity
    {
        False = 0,
        True = 1,
    }
}