//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;

    public class Keys
    {
        [JsonProperty("alg")]
        public string? Alg { get; set; }

        [JsonProperty("e")]
        public string? E { get; set; }

        [JsonProperty("kid")]
        public string? Kid { get; set; }

        [JsonProperty("kty")]
        public string? Kty { get; set; }

        [JsonProperty("n")]
        public string? N { get; set; }

        [JsonProperty("use")]
        public string? Use { get; set; }
    }
}