//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class MediaContainerWithDecisionCanAutoSync2Type
    {
        private MediaContainerWithDecisionCanAutoSync2Type(string value) { Value = value; }

        public string Value { get; private set; }

        public static MediaContainerWithDecisionCanAutoSync2Type Two1 { get { return new MediaContainerWithDecisionCanAutoSync2Type("2_1"); } }

        public static MediaContainerWithDecisionCanAutoSync2Type Boolean { get { return new MediaContainerWithDecisionCanAutoSync2Type("boolean"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(MediaContainerWithDecisionCanAutoSync2Type v) { return v.Value; }
        public static MediaContainerWithDecisionCanAutoSync2Type FromString(string v) {
            switch(v) {
                case "2_1": return Two1;
                case "boolean": return Boolean;
                default: throw new ArgumentException("Invalid value for MediaContainerWithDecisionCanAutoSync2Type");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MediaContainerWithDecisionCanAutoSync2Type)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(MediaContainerWithDecisionCanAutoSync2.MediaContainerWithDecisionCanAutoSync2Converter))]
    public class MediaContainerWithDecisionCanAutoSync2
    {
        public MediaContainerWithDecisionCanAutoSync2(MediaContainerWithDecisionCanAutoSync2Type type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Two1? Two1 { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        public MediaContainerWithDecisionCanAutoSync2Type Type { get; set; }
        public static MediaContainerWithDecisionCanAutoSync2 CreateTwo1(Two1 two1)
        {
            MediaContainerWithDecisionCanAutoSync2Type typ = MediaContainerWithDecisionCanAutoSync2Type.Two1;

            MediaContainerWithDecisionCanAutoSync2 res = new MediaContainerWithDecisionCanAutoSync2(typ);
            res.Two1 = two1;
            return res;
        }
        public static MediaContainerWithDecisionCanAutoSync2 CreateBoolean(bool boolean)
        {
            MediaContainerWithDecisionCanAutoSync2Type typ = MediaContainerWithDecisionCanAutoSync2Type.Boolean;

            MediaContainerWithDecisionCanAutoSync2 res = new MediaContainerWithDecisionCanAutoSync2(typ);
            res.Boolean = boolean;
            return res;
        }

        public class MediaContainerWithDecisionCanAutoSync2Converter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(MediaContainerWithDecisionCanAutoSync2);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new MediaContainerWithDecisionCanAutoSync2(MediaContainerWithDecisionCanAutoSync2Type.Two1)
                    {
                        Two1 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Two1>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Two1), new MediaContainerWithDecisionCanAutoSync2(MediaContainerWithDecisionCanAutoSync2Type.Two1), "Two1"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new MediaContainerWithDecisionCanAutoSync2(MediaContainerWithDecisionCanAutoSync2Type.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                MediaContainerWithDecisionCanAutoSync2 res = (MediaContainerWithDecisionCanAutoSync2)value;

                if (res.Two1 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Two1));
                    return;
                }

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods.");
            }

        }

    }
}