//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Audio bitrate mode (cbr or vbr).
    /// </summary>
    public enum MediaContainerWithDecisionBitrateMode
    {
        [JsonProperty("cbr")]
        Cbr,
        [JsonProperty("vbr")]
        Vbr,
    }

    public static class MediaContainerWithDecisionBitrateModeExtension
    {
        public static string Value(this MediaContainerWithDecisionBitrateMode value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static MediaContainerWithDecisionBitrateMode ToEnum(this string value)
        {
            foreach(var field in typeof(MediaContainerWithDecisionBitrateMode).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is MediaContainerWithDecisionBitrateMode)
                    {
                        return (MediaContainerWithDecisionBitrateMode)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum MediaContainerWithDecisionBitrateMode");
        }
    }
}