//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class MediaContainerWithDecisionCanAutoSyncType
    {
        private MediaContainerWithDecisionCanAutoSyncType(string value) { Value = value; }

        public string Value { get; private set; }

        public static MediaContainerWithDecisionCanAutoSyncType Boolean { get { return new MediaContainerWithDecisionCanAutoSyncType("boolean"); } }

        public static MediaContainerWithDecisionCanAutoSyncType MediaContainerWithDecisionCanAutoSync2 { get { return new MediaContainerWithDecisionCanAutoSyncType("MediaContainerWithDecision_canAutoSync_2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(MediaContainerWithDecisionCanAutoSyncType v) { return v.Value; }
        public static MediaContainerWithDecisionCanAutoSyncType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "MediaContainerWithDecision_canAutoSync_2": return MediaContainerWithDecisionCanAutoSync2;
                default: throw new ArgumentException("Invalid value for MediaContainerWithDecisionCanAutoSyncType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((MediaContainerWithDecisionCanAutoSyncType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Indicates if the stream can auto-sync.
    /// </summary>
    [JsonConverter(typeof(MediaContainerWithDecisionCanAutoSync.MediaContainerWithDecisionCanAutoSyncConverter))]
    public class MediaContainerWithDecisionCanAutoSync
    {
        public MediaContainerWithDecisionCanAutoSync(MediaContainerWithDecisionCanAutoSyncType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public MediaContainerWithDecisionCanAutoSync2? MediaContainerWithDecisionCanAutoSync2 { get; set; }

        public MediaContainerWithDecisionCanAutoSyncType Type { get; set; }
        public static MediaContainerWithDecisionCanAutoSync CreateBoolean(bool boolean)
        {
            MediaContainerWithDecisionCanAutoSyncType typ = MediaContainerWithDecisionCanAutoSyncType.Boolean;

            MediaContainerWithDecisionCanAutoSync res = new MediaContainerWithDecisionCanAutoSync(typ);
            res.Boolean = boolean;
            return res;
        }
        public static MediaContainerWithDecisionCanAutoSync CreateMediaContainerWithDecisionCanAutoSync2(MediaContainerWithDecisionCanAutoSync2 mediaContainerWithDecisionCanAutoSync2)
        {
            MediaContainerWithDecisionCanAutoSyncType typ = MediaContainerWithDecisionCanAutoSyncType.MediaContainerWithDecisionCanAutoSync2;

            MediaContainerWithDecisionCanAutoSync res = new MediaContainerWithDecisionCanAutoSync(typ);
            res.MediaContainerWithDecisionCanAutoSync2 = mediaContainerWithDecisionCanAutoSync2;
            return res;
        }

        public class MediaContainerWithDecisionCanAutoSyncConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(MediaContainerWithDecisionCanAutoSync);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new MediaContainerWithDecisionCanAutoSync(MediaContainerWithDecisionCanAutoSyncType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new MediaContainerWithDecisionCanAutoSync(MediaContainerWithDecisionCanAutoSyncType.MediaContainerWithDecisionCanAutoSync2)
                    {
                        MediaContainerWithDecisionCanAutoSync2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<MediaContainerWithDecisionCanAutoSync2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(MediaContainerWithDecisionCanAutoSync2), new MediaContainerWithDecisionCanAutoSync(MediaContainerWithDecisionCanAutoSyncType.MediaContainerWithDecisionCanAutoSync2), "MediaContainerWithDecisionCanAutoSync2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                MediaContainerWithDecisionCanAutoSync res = (MediaContainerWithDecisionCanAutoSync)value;

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.MediaContainerWithDecisionCanAutoSync2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MediaContainerWithDecisionCanAutoSync2));
                    return;
                }
            }

        }

    }
}