//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;

    /// <summary>
    /// Real-time playback state change notification.
    /// </summary>
    public class PlaySessionStateNotification
    {
        public string? Controllable { get; set; }

        public string? Guid { get; set; }

        public string? Key { get; set; }

        public long? PlayQueueID { get; set; }

        public long? PlayQueueItemID { get; set; }

        public string? RatingKey { get; set; }

        public string? SessionKey { get; set; }

        public Models.Components.State? State { get; set; }

        public string? TranscodeSession { get; set; }

        public string? Url { get; set; }

        public long? ViewOffset { get; set; }
    }
}