//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;

    public class PlayQueueResponse
    {
        /// <summary>
        /// The ID of the play queue, which is used in subsequent requests.
        /// </summary>
        [JsonProperty("playQueueID")]
        public long? PlayQueueID { get; set; }

        /// <summary>
        /// Defines where the "Up Next" region starts.
        /// </summary>
        [JsonProperty("playQueueLastAddedItemID")]
        public string? PlayQueueLastAddedItemID { get; set; }

        /// <summary>
        /// The queue item ID of the currently selected  item.
        /// </summary>
        [JsonProperty("playQueueSelectedItemID")]
        public long? PlayQueueSelectedItemID { get; set; }

        /// <summary>
        /// The offset of the selected item in the play queue, from the beginning of the queue.
        /// </summary>
        [JsonProperty("playQueueSelectedItemOffset")]
        public long? PlayQueueSelectedItemOffset { get; set; }

        /// <summary>
        /// The metadata item ID of the currently selected item (matches `ratingKey` attribute in metadata item if the media provider is a library).
        /// </summary>
        [JsonProperty("playQueueSelectedMetadataItemID")]
        public long? PlayQueueSelectedMetadataItemID { get; set; }

        /// <summary>
        /// Whether or not the queue is shuffled.
        /// </summary>
        [JsonProperty("playQueueShuffled")]
        public bool? PlayQueueShuffled { get; set; }

        /// <summary>
        /// The original URI used to create the play queue.
        /// </summary>
        [JsonProperty("playQueueSourceURI")]
        public string? PlayQueueSourceURI { get; set; }

        /// <summary>
        /// The total number of items in the play queue.
        /// </summary>
        [JsonProperty("playQueueTotalCount")]
        public long? PlayQueueTotalCount { get; set; }

        /// <summary>
        /// The version of the play queue. It increments every time a change is made to the play queue to assist clients in knowing when to refresh.
        /// </summary>
        [JsonProperty("playQueueVersion")]
        public long? PlayQueueVersion { get; set; }
    }
}