//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class SlashGetResponses200AllowSyncType
    {
        private SlashGetResponses200AllowSyncType(string value) { Value = value; }

        public string Value { get; private set; }

        public static SlashGetResponses200AllowSyncType Boolean { get { return new SlashGetResponses200AllowSyncType("boolean"); } }

        public static SlashGetResponses200AllowSyncType SlashGetResponses200AllowSync2 { get { return new SlashGetResponses200AllowSyncType("slash-get-responses-200_allowSync_2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(SlashGetResponses200AllowSyncType v) { return v.Value; }
        public static SlashGetResponses200AllowSyncType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "slash-get-responses-200_allowSync_2": return SlashGetResponses200AllowSync2;
                default: throw new ArgumentException("Invalid value for SlashGetResponses200AllowSyncType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SlashGetResponses200AllowSyncType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(SlashGetResponses200AllowSync.SlashGetResponses200AllowSyncConverter))]
    public class SlashGetResponses200AllowSync
    {
        public SlashGetResponses200AllowSync(SlashGetResponses200AllowSyncType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public SlashGetResponses200AllowSync2? SlashGetResponses200AllowSync2 { get; set; }

        public SlashGetResponses200AllowSyncType Type { get; set; }
        public static SlashGetResponses200AllowSync CreateBoolean(bool boolean)
        {
            SlashGetResponses200AllowSyncType typ = SlashGetResponses200AllowSyncType.Boolean;

            SlashGetResponses200AllowSync res = new SlashGetResponses200AllowSync(typ);
            res.Boolean = boolean;
            return res;
        }
        public static SlashGetResponses200AllowSync CreateSlashGetResponses200AllowSync2(SlashGetResponses200AllowSync2 slashGetResponses200AllowSync2)
        {
            SlashGetResponses200AllowSyncType typ = SlashGetResponses200AllowSyncType.SlashGetResponses200AllowSync2;

            SlashGetResponses200AllowSync res = new SlashGetResponses200AllowSync(typ);
            res.SlashGetResponses200AllowSync2 = slashGetResponses200AllowSync2;
            return res;
        }

        public class SlashGetResponses200AllowSyncConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(SlashGetResponses200AllowSync);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new SlashGetResponses200AllowSync(SlashGetResponses200AllowSyncType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new SlashGetResponses200AllowSync(SlashGetResponses200AllowSyncType.SlashGetResponses200AllowSync2)
                    {
                        SlashGetResponses200AllowSync2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SlashGetResponses200AllowSync2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SlashGetResponses200AllowSync2), new SlashGetResponses200AllowSync(SlashGetResponses200AllowSyncType.SlashGetResponses200AllowSync2), "SlashGetResponses200AllowSync2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                SlashGetResponses200AllowSync res = (SlashGetResponses200AllowSync)value;

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.SlashGetResponses200AllowSync2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SlashGetResponses200AllowSync2));
                    return;
                }
            }

        }

    }
}