//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;

    /// <summary>
    /// Server status notification (e.g. library scan complete).
    /// </summary>
    public class StatusNotification
    {
        public string? Title { get; set; }

        public string? Description { get; set; }

        public string? Type { get; set; }
    }
}