//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// A simple success indicator for operations that return no meaningful data.
    /// </summary>
    public class SuccessResponse
    {
        [JsonProperty("success")]
        public bool? Success { get; set; }
    }
}