//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Components
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;

    public class TokenExchangeRequest
    {
        /// <summary>
        /// Unique client identifier.
        /// </summary>
        [JsonProperty("clientIdentifier")]
        public string? ClientIdentifier { get; set; }

        /// <summary>
        /// JWT token to exchange for a Plex auth token.
        /// </summary>
        [JsonProperty("jwt")]
        public string? Jwt { get; set; }

        /// <summary>
        /// Requested scope for the token.
        /// </summary>
        [JsonProperty("scope")]
        public string? Scope { get; set; }
    }
}