//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Errors
{
    using LukeHagar.PlexAPI.SDK.Models.Errors;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;

    public class ErrorPayload
    {
        [JsonProperty("errors")]
        public List<Errors>? Errors { get; set; }
    }

    /// <summary>
    /// Unauthorized.
    /// </summary>
    public class Error : PlexAPIError
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public ErrorPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use Error.Payload.Errors instead.")]
        public List<Errors>? Errors { get; set; }

        public Error(
            ErrorPayload payload,
            HttpResponseMessage rawResponse,
            string body
        ): base("API error occurred", rawResponse, body)
        {
           Payload = payload;

           #pragma warning disable CS0618
           Errors = payload.Errors;
           #pragma warning restore CS0618
        }
    }
}