//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Models.Requests;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class GetPlaylistGeneratorItemsSkipParentType
    {
        private GetPlaylistGeneratorItemsSkipParentType(string value) { Value = value; }

        public string Value { get; private set; }

        public static GetPlaylistGeneratorItemsSkipParentType Boolean { get { return new GetPlaylistGeneratorItemsSkipParentType("boolean"); } }

        public static GetPlaylistGeneratorItemsSkipParentType GetPlaylistGeneratorItemsSkipParent2 { get { return new GetPlaylistGeneratorItemsSkipParentType("getPlaylistGeneratorItems_skipParent_2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(GetPlaylistGeneratorItemsSkipParentType v) { return v.Value; }
        public static GetPlaylistGeneratorItemsSkipParentType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "getPlaylistGeneratorItems_skipParent_2": return GetPlaylistGeneratorItemsSkipParent2;
                default: throw new ArgumentException("Invalid value for GetPlaylistGeneratorItemsSkipParentType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((GetPlaylistGeneratorItemsSkipParentType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// When present on an episode or track item, indicates parent should be skipped in favor of grandparent (show).
    /// </summary>
    [JsonConverter(typeof(GetPlaylistGeneratorItemsSkipParent.GetPlaylistGeneratorItemsSkipParentConverter))]
    public class GetPlaylistGeneratorItemsSkipParent
    {
        public GetPlaylistGeneratorItemsSkipParent(GetPlaylistGeneratorItemsSkipParentType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public GetPlaylistGeneratorItemsSkipParent2? GetPlaylistGeneratorItemsSkipParent2 { get; set; }

        public GetPlaylistGeneratorItemsSkipParentType Type { get; set; }
        public static GetPlaylistGeneratorItemsSkipParent CreateBoolean(bool boolean)
        {
            GetPlaylistGeneratorItemsSkipParentType typ = GetPlaylistGeneratorItemsSkipParentType.Boolean;

            GetPlaylistGeneratorItemsSkipParent res = new GetPlaylistGeneratorItemsSkipParent(typ);
            res.Boolean = boolean;
            return res;
        }
        public static GetPlaylistGeneratorItemsSkipParent CreateGetPlaylistGeneratorItemsSkipParent2(GetPlaylistGeneratorItemsSkipParent2 getPlaylistGeneratorItemsSkipParent2)
        {
            GetPlaylistGeneratorItemsSkipParentType typ = GetPlaylistGeneratorItemsSkipParentType.GetPlaylistGeneratorItemsSkipParent2;

            GetPlaylistGeneratorItemsSkipParent res = new GetPlaylistGeneratorItemsSkipParent(typ);
            res.GetPlaylistGeneratorItemsSkipParent2 = getPlaylistGeneratorItemsSkipParent2;
            return res;
        }

        public class GetPlaylistGeneratorItemsSkipParentConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(GetPlaylistGeneratorItemsSkipParent);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new GetPlaylistGeneratorItemsSkipParent(GetPlaylistGeneratorItemsSkipParentType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new GetPlaylistGeneratorItemsSkipParent(GetPlaylistGeneratorItemsSkipParentType.GetPlaylistGeneratorItemsSkipParent2)
                    {
                        GetPlaylistGeneratorItemsSkipParent2 = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<GetPlaylistGeneratorItemsSkipParent2>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(GetPlaylistGeneratorItemsSkipParent2), new GetPlaylistGeneratorItemsSkipParent(GetPlaylistGeneratorItemsSkipParentType.GetPlaylistGeneratorItemsSkipParent2), "GetPlaylistGeneratorItemsSkipParent2"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                GetPlaylistGeneratorItemsSkipParent res = (GetPlaylistGeneratorItemsSkipParent)value;

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.GetPlaylistGeneratorItemsSkipParent2 != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.GetPlaylistGeneratorItemsSkipParent2));
                    return;
                }
            }

        }

    }
}