//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Feature key identifier.
    /// </summary>
    public enum Key
    {
        [JsonProperty("search")]
        Search,
        [JsonProperty("metadata")]
        Metadata,
        [JsonProperty("content")]
        Content,
        [JsonProperty("match")]
        Match,
        [JsonProperty("manage")]
        Manage,
        [JsonProperty("timeline")]
        Timeline,
        [JsonProperty("rate")]
        Rate,
        [JsonProperty("playqueue")]
        Playqueue,
        [JsonProperty("playlist")]
        Playlist,
        [JsonProperty("subscribe")]
        Subscribe,
        [JsonProperty("promoted")]
        Promoted,
        [JsonProperty("continuewatching")]
        Continuewatching,
        [JsonProperty("collection")]
        Collection,
        [JsonProperty("actions")]
        Actions,
        [JsonProperty("imagetranscoder")]
        Imagetranscoder,
        [JsonProperty("queryParser")]
        QueryParser,
        [JsonProperty("grid")]
        Grid,
    }

    public static class KeyExtension
    {
        public static string Value(this Key value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Key ToEnum(this string value)
        {
            foreach(var field in typeof(Key).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is Key)
                    {
                        return (Key)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum Key");
        }
    }
}