//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK.Models.Requests
{
    using LukeHagar.PlexAPI.SDK.Models.Requests;
    using LukeHagar.PlexAPI.SDK.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class SkipChildrenType
    {
        private SkipChildrenType(string value) { Value = value; }

        public string Value { get; private set; }

        public static SkipChildrenType Boolean { get { return new SkipChildrenType("boolean"); } }

        public static SkipChildrenType Two { get { return new SkipChildrenType("2"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(SkipChildrenType v) { return v.Value; }
        public static SkipChildrenType FromString(string v) {
            switch(v) {
                case "boolean": return Boolean;
                case "2": return Two;
                default: throw new ArgumentException("Invalid value for SkipChildrenType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SkipChildrenType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// When found on a show item, indicates that the children (seasons) should be skipped in favor of the grandchildren (episodes). Useful for mini-series, etc.
    /// </summary>
    [JsonConverter(typeof(SkipChildren.SkipChildrenConverter))]
    public class SkipChildren
    {
        public SkipChildren(SkipChildrenType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public bool? Boolean { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public Models.Requests.Two? Two { get; set; }

        public SkipChildrenType Type { get; set; }
        public static SkipChildren CreateBoolean(bool boolean)
        {
            SkipChildrenType typ = SkipChildrenType.Boolean;

            SkipChildren res = new SkipChildren(typ);
            res.Boolean = boolean;
            return res;
        }
        public static SkipChildren CreateTwo(Models.Requests.Two two)
        {
            SkipChildrenType typ = SkipChildrenType.Two;

            SkipChildren res = new SkipChildren(typ);
            res.Two = two;
            return res;
        }

        public class SkipChildrenConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(SkipChildren);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    var converted = Convert.ToBoolean(json);
                    return new SkipChildren(SkipChildrenType.Boolean)
                    {
                        Boolean = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                try
                {
                    return new SkipChildren(SkipChildrenType.Two)
                    {
                        Two = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Models.Requests.Two>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Models.Requests.Two), new SkipChildren(SkipChildrenType.Two), "Two"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                SkipChildren res = (SkipChildren)value;

                if (res.Boolean != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Boolean));
                    return;
                }

                if (res.Two != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Two));
                    return;
                }
            }

        }

    }
}