//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace LukeHagar.PlexAPI.SDK
{
    using LukeHagar.PlexAPI.SDK.Hooks;
    using LukeHagar.PlexAPI.SDK.Models.Components;
    using LukeHagar.PlexAPI.SDK.Models.Errors;
    using LukeHagar.PlexAPI.SDK.Models.Requests;
    using LukeHagar.PlexAPI.SDK.Utils;
    using LukeHagar.PlexAPI.SDK.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading.Tasks;

    /// <summary>
    /// Endpoints for manipulating playlists.
    /// </summary>
    public interface ILibraryPlaylists
    {
        /// <summary>
        /// Create a Playlist.
        /// </summary>
        /// <remarks>
        /// Create a new playlist. By default the playlist is blank.
        /// </remarks>
        /// <param name="request">A <see cref="CreatePlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="CreatePlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<CreatePlaylistResponse> CreatePlaylistAsync(CreatePlaylistRequest? request = null);

        /// <summary>
        /// Upload.
        /// </summary>
        /// <remarks>
        /// Imports m3u playlists by passing a path on the server to scan for m3u-formatted playlist files, or a path to a single playlist file.
        /// </remarks>
        /// <param name="request">A <see cref="UploadPlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="UploadPlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<UploadPlaylistResponse> UploadPlaylistAsync(UploadPlaylistRequest? request = null);

        /// <summary>
        /// Delete a Playlist.
        /// </summary>
        /// <remarks>
        /// Deletes a playlist by provided id.
        /// </remarks>
        /// <param name="request">A <see cref="DeletePlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="DeletePlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<DeletePlaylistResponse> DeletePlaylistAsync(DeletePlaylistRequest request);

        /// <summary>
        /// Editing a Playlist.
        /// </summary>
        /// <remarks>
        /// Edits a playlist in the same manner as <a href="#tag/Provider/operation/metadataPutItem">editing metadata</a>
        /// </remarks>
        /// <param name="request">A <see cref="UpdatePlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="UpdatePlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<UpdatePlaylistResponse> UpdatePlaylistAsync(UpdatePlaylistRequest request);

        /// <summary>
        /// Get a playlist's generators.
        /// </summary>
        /// <remarks>
        /// Get all the generators in a playlist.
        /// </remarks>
        /// <param name="request">A <see cref="GetPlaylistGeneratorsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="GetPlaylistGeneratorsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<GetPlaylistGeneratorsResponse> GetPlaylistGeneratorsAsync(GetPlaylistGeneratorsRequest request);

        /// <summary>
        /// Clearing a playlist.
        /// </summary>
        /// <remarks>
        /// Clears a playlist, only works with dumb playlists. Returns the playlist.
        /// </remarks>
        /// <param name="request">A <see cref="ClearPlaylistItemsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="ClearPlaylistItemsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<ClearPlaylistItemsResponse> ClearPlaylistItemsAsync(ClearPlaylistItemsRequest request);

        /// <summary>
        /// Adding to  a Playlist.
        /// </summary>
        /// <remarks>
        /// Adds a generator to a playlist, same parameters as the POST above. With a dumb playlist, this adds the specified items to the playlist. With a smart playlist, passing a new `uri` parameter replaces the rules for the playlist. Returns the playlist.
        /// </remarks>
        /// <param name="request">A <see cref="AddPlaylistItemsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="AddPlaylistItemsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<AddPlaylistItemsResponse> AddPlaylistItemsAsync(AddPlaylistItemsRequest request);

        /// <summary>
        /// Delete a Generator.
        /// </summary>
        /// <remarks>
        /// Deletes an item from a playlist. Only works with dumb playlists.
        /// </remarks>
        /// <param name="request">A <see cref="DeletePlaylistItemRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="DeletePlaylistItemResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<DeletePlaylistItemResponse> DeletePlaylistItemAsync(DeletePlaylistItemRequest request);

        /// <summary>
        /// Get a playlist generator.
        /// </summary>
        /// <remarks>
        /// Get a playlist's generator.  Only used for optimized versions.
        /// </remarks>
        /// <param name="request">A <see cref="GetPlaylistGeneratorRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="GetPlaylistGeneratorResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<GetPlaylistGeneratorResponse> GetPlaylistGeneratorAsync(GetPlaylistGeneratorRequest request);

        /// <summary>
        /// Get a playlist generator's items.
        /// </summary>
        /// <remarks>
        /// Get a playlist generator's items.
        /// </remarks>
        /// <param name="request">A <see cref="GetPlaylistGeneratorItemsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="GetPlaylistGeneratorItemsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<GetPlaylistGeneratorItemsResponse> GetPlaylistGeneratorItemsAsync(
            GetPlaylistGeneratorItemsRequest request
        );

        /// <summary>
        /// Moving items in a playlist.
        /// </summary>
        /// <remarks>
        /// Moves an item in a playlist. Only works with dumb playlists.
        /// </remarks>
        /// <param name="request">A <see cref="MovePlaylistItemRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="MovePlaylistItemResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<MovePlaylistItemResponse> MovePlaylistItemAsync(MovePlaylistItemRequest request);

        /// <summary>
        /// Reprocess a generator.
        /// </summary>
        /// <remarks>
        /// Make a generator reprocess (refresh).
        /// </remarks>
        /// <param name="request">A <see cref="RefreshPlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="RefreshPlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public  Task<RefreshPlaylistResponse> RefreshPlaylistAsync(RefreshPlaylistRequest request);
    }

    /// <summary>
    /// Endpoints for manipulating playlists.
    /// </summary>
    public class LibraryPlaylists: ILibraryPlaylists
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        public LibraryPlaylists(SDKConfig config)
        {
            SDKConfiguration = config;
        }

        /// <summary>
        /// Create a Playlist.
        /// </summary>
        /// <remarks>
        /// Create a new playlist. By default the playlist is blank.
        /// </remarks>
        /// <param name="request">A <see cref="CreatePlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="CreatePlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<CreatePlaylistResponse> CreatePlaylistAsync(CreatePlaylistRequest? request = null)
        {
            if (request == null)
            {
                request = new CreatePlaylistRequest();
            }
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "createPlaylist", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    MediaContainerWithPlaylistMetadata obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<MediaContainerWithPlaylistMetadata>(httpResponseBody, NullValueHandling.Include);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into MediaContainerWithPlaylistMetadata.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new CreatePlaylistResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.MediaContainerWithPlaylistMetadata = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Upload.
        /// </summary>
        /// <remarks>
        /// Imports m3u playlists by passing a path on the server to scan for m3u-formatted playlist files, or a path to a single playlist file.
        /// </remarks>
        /// <param name="request">A <see cref="UploadPlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="UploadPlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<UploadPlaylistResponse> UploadPlaylistAsync(UploadPlaylistRequest? request = null)
        {
            if (request == null)
            {
                request = new UploadPlaylistRequest();
            }
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/upload", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "*/*");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "uploadPlaylist", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                return new UploadPlaylistResponse()
                {
                    StatusCode = responseStatusCode,
                    ContentType = contentType,
                    RawResponse = httpResponse
                };
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Delete a Playlist.
        /// </summary>
        /// <remarks>
        /// Deletes a playlist by provided id.
        /// </remarks>
        /// <param name="request">A <see cref="DeletePlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="DeletePlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<DeletePlaylistResponse> DeletePlaylistAsync(DeletePlaylistRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Delete, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "*/*");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "deletePlaylist", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 204)
            {
                return new DeletePlaylistResponse()
                {
                    StatusCode = responseStatusCode,
                    ContentType = contentType,
                    RawResponse = httpResponse
                };
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Editing a Playlist.
        /// </summary>
        /// <remarks>
        /// Edits a playlist in the same manner as <a href="#tag/Provider/operation/metadataPutItem">editing metadata</a>
        /// </remarks>
        /// <param name="request">A <see cref="UpdatePlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="UpdatePlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<UpdatePlaylistResponse> UpdatePlaylistAsync(UpdatePlaylistRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Put, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "*/*");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "updatePlaylist", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 204)
            {
                return new UpdatePlaylistResponse()
                {
                    StatusCode = responseStatusCode,
                    ContentType = contentType,
                    RawResponse = httpResponse
                };
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Get a playlist's generators.
        /// </summary>
        /// <remarks>
        /// Get all the generators in a playlist.
        /// </remarks>
        /// <param name="request">A <see cref="GetPlaylistGeneratorsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="GetPlaylistGeneratorsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<GetPlaylistGeneratorsResponse> GetPlaylistGeneratorsAsync(
            GetPlaylistGeneratorsRequest request
        )
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/generators", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "getPlaylistGenerators", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GetPlaylistGeneratorsResponseBody obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<GetPlaylistGeneratorsResponseBody>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GetPlaylistGeneratorsResponseBody.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new GetPlaylistGeneratorsResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Clearing a playlist.
        /// </summary>
        /// <remarks>
        /// Clears a playlist, only works with dumb playlists. Returns the playlist.
        /// </remarks>
        /// <param name="request">A <see cref="ClearPlaylistItemsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="ClearPlaylistItemsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<ClearPlaylistItemsResponse> ClearPlaylistItemsAsync(ClearPlaylistItemsRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/items", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Delete, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "clearPlaylistItems", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    MediaContainerWithPlaylistMetadata obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<MediaContainerWithPlaylistMetadata>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into MediaContainerWithPlaylistMetadata.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new ClearPlaylistItemsResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.MediaContainerWithPlaylistMetadata = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Adding to  a Playlist.
        /// </summary>
        /// <remarks>
        /// Adds a generator to a playlist, same parameters as the POST above. With a dumb playlist, this adds the specified items to the playlist. With a smart playlist, passing a new `uri` parameter replaces the rules for the playlist. Returns the playlist.
        /// </remarks>
        /// <param name="request">A <see cref="AddPlaylistItemsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="AddPlaylistItemsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<AddPlaylistItemsResponse> AddPlaylistItemsAsync(AddPlaylistItemsRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/items", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Put, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "addPlaylistItems", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    MediaContainerWithPlaylistMetadata obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<MediaContainerWithPlaylistMetadata>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into MediaContainerWithPlaylistMetadata.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new AddPlaylistItemsResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.MediaContainerWithPlaylistMetadata = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Delete a Generator.
        /// </summary>
        /// <remarks>
        /// Deletes an item from a playlist. Only works with dumb playlists.
        /// </remarks>
        /// <param name="request">A <see cref="DeletePlaylistItemRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="DeletePlaylistItemResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<DeletePlaylistItemResponse> DeletePlaylistItemAsync(DeletePlaylistItemRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/items/{generatorId}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Delete, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "deletePlaylistItem", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    MediaContainerWithPlaylistMetadata obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<MediaContainerWithPlaylistMetadata>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into MediaContainerWithPlaylistMetadata.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new DeletePlaylistItemResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.MediaContainerWithPlaylistMetadata = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Get a playlist generator.
        /// </summary>
        /// <remarks>
        /// Get a playlist's generator.  Only used for optimized versions.
        /// </remarks>
        /// <param name="request">A <see cref="GetPlaylistGeneratorRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="GetPlaylistGeneratorResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<GetPlaylistGeneratorResponse> GetPlaylistGeneratorAsync(GetPlaylistGeneratorRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/items/{generatorId}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "getPlaylistGenerator", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GetPlaylistGeneratorResponseBody obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<GetPlaylistGeneratorResponseBody>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GetPlaylistGeneratorResponseBody.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new GetPlaylistGeneratorResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Get a playlist generator's items.
        /// </summary>
        /// <remarks>
        /// Get a playlist generator's items.
        /// </remarks>
        /// <param name="request">A <see cref="GetPlaylistGeneratorItemsRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="GetPlaylistGeneratorItemsResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<GetPlaylistGeneratorItemsResponse> GetPlaylistGeneratorItemsAsync(
            GetPlaylistGeneratorItemsRequest request
        )
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/items/{generatorId}/items", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "getPlaylistGeneratorItems", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GetPlaylistGeneratorItemsResponseBody obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<GetPlaylistGeneratorItemsResponseBody>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GetPlaylistGeneratorItemsResponseBody.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new GetPlaylistGeneratorItemsResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Moving items in a playlist.
        /// </summary>
        /// <remarks>
        /// Moves an item in a playlist. Only works with dumb playlists.
        /// </remarks>
        /// <param name="request">A <see cref="MovePlaylistItemRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="MovePlaylistItemResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<MovePlaylistItemResponse> MovePlaylistItemAsync(MovePlaylistItemRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/items/{playlistItemId}/move", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Put, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "movePlaylistItem", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    MediaContainerWithPlaylistMetadata obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<MediaContainerWithPlaylistMetadata>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into MediaContainerWithPlaylistMetadata.", httpResponse, httpResponseBody, ex);
                    }

                    var response = new MovePlaylistItemResponse()
                    {
                        StatusCode = responseStatusCode,
                        ContentType = contentType,
                        RawResponse = httpResponse
                    };
                    response.MediaContainerWithPlaylistMetadata = obj;
                    return response;
                }

                throw new Models.Errors.SDKException("Unknown content type received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }


        /// <summary>
        /// Reprocess a generator.
        /// </summary>
        /// <remarks>
        /// Make a generator reprocess (refresh).
        /// </remarks>
        /// <param name="request">A <see cref="RefreshPlaylistRequest"/> parameter.</param>
        /// <returns>An awaitable task that returns a <see cref="RefreshPlaylistResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="request"/> is null.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="SDKException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async  Task<RefreshPlaylistResponse> RefreshPlaylistAsync(RefreshPlaylistRequest request)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            request.Accepts ??= SDKConfiguration.Accepts;
            request.ClientIdentifier ??= SDKConfiguration.ClientIdentifier;
            request.Product ??= SDKConfiguration.Product;
            request.Version ??= SDKConfiguration.Version;
            request.Platform ??= SDKConfiguration.Platform;
            request.PlatformVersion ??= SDKConfiguration.PlatformVersion;
            request.Device ??= SDKConfiguration.Device;
            request.Model ??= SDKConfiguration.Model;
            request.DeviceVendor ??= SDKConfiguration.DeviceVendor;
            request.DeviceName ??= SDKConfiguration.DeviceName;
            request.Marketplace ??= SDKConfiguration.Marketplace;

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/playlists/{playlistId}/items/{generatorId}/{metadataId}/{action}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Put, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);
            HeaderSerializer.PopulateHeaders(ref httpRequest, request);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "*/*");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "refreshPlaylist", null, SDKConfiguration.SecuritySource);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                return new RefreshPlaylistResponse()
                {
                    StatusCode = responseStatusCode,
                    ContentType = contentType,
                    RawResponse = httpResponse
                };
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.SDKException("API error occurred", httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.SDKException("Unknown status code received", httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

    }
}